## Define

In [15]:
from resources.utils import *
from gensim.models import Word2Vec

!mkdir -p tb
!mkdir -p tb/embeddings

mc['github'].list_collection_names()

['users_followers_embeddings',
 'followers',
 'projects',
 'users_following_embeddings',
 'followers_all',
 'users_watches',
 'repos_watches_embeddings',
 'repos_stars_embeddings',
 'users',
 'following']

## Repos

In [16]:
repo_model_name = 'repos_watches_emb_sg_d300_w50_mc200_e50'
repo_model = Word2Vec.load('./models/' + repo_model_name + '.bin')
print(repo_model)

/opt/conda/lib/python3.7/site-packages/smart_open/smart_open_lib.py:398: UserWarning:

This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function

Word2Vec(vocab=84973, size=300, alpha=0.025)

In [17]:
good_rids = []

for rid, r in repo_model.wv.vocab.items():
    if r.count >= 1_000:
        good_rids.append(int(rid))
len(good_rids)

18722

In [18]:
good_rids

[19,
 1226,
 280,
 11603,
 284,
 2561674,
 3189,
 5831963,
 101520307,
 348,
 6180,
 288,
 10313229,
 2812,
 231,
 3981,
 18089783,
 847,
 3085,
 853,
 992,
 14335,
 1362,
 37811,
 1036,
 29261651,
 1344863,
 12031,
 5874,
 337,
 10735,
 1267,
 183,
 1907512,
 964,
 9427,
 1301,
 1691,
 6801328,
 1707,
 1717,
 5101,
 1566,
 1312,
 3601879,
 1911,
 9316,
 7074,
 19034,
 5461,
 2007,
 202,
 17530,
 50703945,
 60488339,
 1229,
 2067,
 4564,
 112576,
 3430,
 2157,
 2160,
 2184,
 9673869,
 11879,
 2233,
 10547585,
 10642813,
 4488,
 2310,
 1155356,
 11313132,
 19626,
 2326,
 4477,
 392,
 2602,
 581,
 5049,
 6313,
 4455,
 31810056,
 8109,
 2279,
 7608,
 3054,
 1334,
 8029,
 11833707,
 3231,
 1896,
 103284,
 89100763,
 93613877,
 3470,
 588,
 553,
 20783,
 33986963,
 25725,
 5711,
 1713,
 3777,
 6093,
 2183,
 10559,
 217063,
 4041,
 9862004,
 4067,
 6782,
 30141,
 4136,
 15762,
 295,
 114167,
 852,
 4492,
 20629,
 61168739,
 72272853,
 1088,
 13454178,
 4612,
 35704,
 129770,
 4788,
 1298,
 5162,
 6820392,
 4765,
 4708601,
 1165,
 1431,
 4739,
 3746639,
 1085,
 2558,
 839476,
 5413,
 5516,
 5767,
 6489,
 22370,
 5626,
 3805,
 5167,
 4876188,
 5692,
 6009,
 334,
 5659677,
 931,
 26667,
 6159,
 728838,
 72294799,
 23326,
 3214347,
 10998645,
 17796,
 147,
 2916055,
 14477484,
 35019404,
 6814,
 7061,
 16411922,
 55,
 900,
 1528221,
 76442,
 48040350,
 37,
 5640,
 11989,
 18795,
 30938759,
 28557277,
 7317,
 31849,
 7770,
 2045,
 42738,
 7982,
 60377505,
 22091370,
 3825551,
 37561753,
 10175046,
 55877825,
 8390,
 8373,
 12455,
 2847808,
 3377,
 1349059,
 9626183,
 411,
 27586452,
 18475,
 31689,
 22791,
 8824,
 88669885,
 2822,
 15698,
 17802,
 2093,
 3684,
 4454,
 10502,
 8111,
 17165,
 11005,
 9431,
 11744,
 13021,
 310,
 11344045,
 1018,
 27356,
 36955,
 3137,
 3174,
 1957,
 12682853,
 4316375,
 41325830,
 9703,
 4234273,
 4964,
 31499094,
 3565023,
 1678,
 47186639,
 3722347,
 10824,
 20088,
 368502,
 5128,
 11184,
 12811549,
 2791,
 12813026,
 2497,
 13430334,
 2922081,
 11450,
 12198118,
 5870189,
 4563494,
 1432,
 11928,
 854407,
 3595,
 683351,
 11036506,
 6597,
 4503,
 5225,
 12459,
 9848144,
 10425724,
 12558,
 20428514,
 10045,
 34896252,
 27415397,
 2696,
 8124,
 21280,
 12830,
 2634,
 4952344,
 1729,
 8352,
 41885,
 17384,
 2247,
 5520,
 10818187,
 14328,
 77717274,
 8017772,
 3894,
 10856,
 316,
 2344,
 11825,
 39330,
 13511,
 538741,
 28485,
 8855674,
 13424293,
 634,
 112249,
 21382248,
 19388,
 14714,
 11902,
 29066970,
 252,
 23995,
 48699687,
 5603,
 27601818,
 23138,
 15752,
 45696853,
 1449,
 34229160,
 15939,
 3040416,
 16968,
 1735275,
 7751311,
 4307,
 4560965,
 11854104,
 937,
 17971,
 29914,
 51173387,
 8127,
 18411,
 37316,
 18535,
 1372,
 6015719,
 18716,
 708,
 34,
 19634548,
 19550,
 19117,
 27142,
 6013,
 2784,
 11821,
 12132,
 74717642,
 340,
 19258,
 4516,
 1434,
 19317,
 19600,
 10938134,
 3200,
 10312696,
 54734467,
 7231843,
 32418929,
 5209,
 10394777,
 2302110,
 663,
 20786,
 11630,
 8866528,
 12056419,
 13453519,
 10736,
 14877,
 20950,
 1920,
 1809,
 11705644,
 82188750,
 11117,
 21485,
 8184,
 20891188,
 24843238,
 5124,
 22462,
 1270737,
 5428284,
 3719,
 12770920,
 89364,
 7172,
 22920,
 20834425,
 6690462,
 33173036,
 3816,
 11125,
 9737671,
 35734,
 4826,
 24293,
 528,
 540,
 13465629,
 3928911,
 6359,
 10632,
 2668,
 42326,
 72968333,
 25991,
 788,
 25997,
 26185,
 4021,
 26361,
 68597,
 5495,
 3516,
 431,
 2675,
 6177,
 4538,
 23043,
 26591,
 26688,
 15870,
 31402,
 3644,
 26728,
 40726,
 15149419,
 1482407,
 862,
 10537,
 2247564,
 1007,
 20477,
 18975889,
 31480,
 7740,
 39902,
 67299844,
 1359660,
 2539527,
 54007,
 10941284,
 21578,
 2247922,
 64349486,
 9861851,
 69293900,
 3656,
 27564,
 22528,
 27550,
 5323,
 8540,
 33743357,
 7933,
 4198417,
 105156,
 1486,
 62775,
 26624,
 12253,
 5839499,
 7590868,
 52463,
 25101327,
 1615,
 34903,
 29671,
 29173661,
 19691,
 125754,
 29931332,
 1537,
 2691,
 11959,
 20282,
 15756,
 19806,
 8256,
 5313,
 18089,
 18085,
 4695228,
 22587,
 32833,
 12047270,
 34014,
 76732,
 55275,
 11072234,
 5230,
 4846,
 1743,
 1842,
 9570005,
 3095,
 36636803,
 67214508,
 62379381,
 4303414,
 341854,
 7528,
 10792136,
 35846,
 24888,
 12885,
 33123929,
 129776,
 6026,
 12718778,
 390,
 2968,
 4571553,
 36768,
 11851,
 15571,
 37177,
 48868,
 99408541,
 105757646,
 6815,
 1431249,
 37802,
 250,
 24187,
 225764,
 81457351,
 33837,
 14073,
 1060,
 15215,
 38717,
 2236,
 12159636,
 39015,
 10798,
 837,
 2301,
 3870950,
 7058,
 12158,
 8816049,
 4430857,
 25821930,
 19860,
 6550,
 22091899,
 66152137,
 40842,
 8552677,
 9178939,
 36908368,
 17729147,
 1273,
 1749436,
 9698210,
 997968,
 26636,
 864,
 1768,
 31283,
 2112,
 25323,
 33335847,
 5378,
 3144,
 26259,
 2560,
 28376,
 4485960,
 4388,
 27113,
 2838632,
 8547,
 114,
 95246,
 1930,
 43671,
 8214553,
 33332,
 3912,
 292185,
 1637,
 7799,
 291,
 14680814,
 15663263,
 2320,
 55885423,
 7976200,
 23830,
 21416,
 44486,
 29304481,
 30995323,
 22019,
 32477942,
 68142909,
 867,
 28492432,
 1416,
 12652296,
 1041,
 36159,
 49868807,
 45658,
 12368,
 8195,
 608,
 26417,
 5322471,
 46907,
 7535679,
 1207,
 20096,
 8143414,
 28315,
 10886,
 6223,
 20281355,
 86523454,
 331,
 10237904,
 15022227,
 32173380,
 8342186,
 29527,
 14979838,
 12258,
 2498,
 10750154,
 48764,
 30012,
 3227,
 50053,
 17387028,
 45827625,
 47768,
 12923,
 12343173,
 10408,
 1941,
 10349838,
 56363369,
 30076099,
 519,
 3281281,
 11423,
 3087647,
 37854188,
 61456975,
 12802222,
 120921603,
 68190380,
 3129,
 2876,
 1953978,
 4101,
 354,
 696102,
 26760,
 7949,
 43574,
 54025,
 10940,
 28327678,
 2727,
 2055,
 6360,
 218426,
 6023628,
 5647300,
 10912,
 13408475,
 54129,
 19996,
 6087,
 7931007,
 55219,
 596712,
 20597272,
 2990,
 11672304,
 19342324,
 20886510,
 6567925,
 47395837,
 6139516,
 40062388,
 5696,
 11794421,
 2569,
 10887,
 56341,
 6705344,
 8108,
 95217438,
 16415632,
 25031,
 10972,
 3984,
 37241922,
 6017423,
 3577209,
 31322879,
 84812,
 2733,
 4679055,
 3209,
 60572,
 2329747,
 14622,
 3182,
 799,
 39143175,
 59866,
 10478608,
 33578321,
 12752080,
 30200006,
 6167821,
 9283125,
 3419130,
 1043,
 6641,
 2931,
 3676758,
 496,
 41004,
 10755424,
 23703003,
 9808205,
 8514,
 14061,
 19593,
 10412,
 10010,
 37731,
 63355,
 11130723,
 2122,
 68810,
 43792747,
 7657,
 6445576,
 4706454,
 28497,
 1654,
 1646,
 2185,
 41569804,
 19616,
 16820,
 23203,
 9459,
 12208029,
 54351,
 7545941,
 23970,
 17735,
 17263,
 20769,
 10815238,
 44639,
 56118,
 1122,
 53170,
 613768,
 489,
 27033,
 42446,
 1620,
 4416136,
 6437914,
 16801,
 29425272,
 66267,
 22862,
 5103953,
 27471,
 10042,
 10777706,
 5464,
 83460809,
 70599002,
 20839,
 2664,
 18419,
 2635,
 2622698,
 26258803,
 27693,
 50083,
 9864388,
 17160540,
 33145,
 82097,
 20429,
 24326,
 35706,
 48360541,
 83157838,
 33357,
 12668167,
 49841417,
 29261981,
 10575,
 1394906,
 5263,
 15845303,
 274,
 11364132,
 32023,
 9663874,
 39721,
 1526285,
 15841,
 9458023,
 23834,
 13752290,
 627,
 23052,
 8335,
 10391155,
 23938,
 33640872,
 10860779,
 149585,
 572,
 8052452,
 7309,
 16948,
 5791,
 14609,
 6931752,
 5349,
 5312,
 26073,
 15791422,
 235,
 13668,
 45313,
 11371,
 39335,
 4986,
 3246,
 3538,
 6845,
 14342,
 32136,
 6050,
 149332,
 530,
 6558,
 3473,
 10933568,
 3867,
 44310621,
 20150840,
 43786903,
 43931904,
 3787,
 4095,
 27329,
 2880,
 11884,
 775774,
 111202780,
 4108,
 3217567,
 6785,
 9664377,
 6866209,
 64966,
 14915,
 8835,
 2886,
 6336782,
 34788,
 2849,
 22131741,
 18742,
 20875,
 4957133,
 96553,
 8525,
 51848,
 12187659,
 13536374,
 51579,
 19106,
 4135,
 60967210,
 1969027,
 16100,
 33798353,
 4929,
 5022,
 251,
 1173,
 11193,
 13038717,
 15605267,
 11074872,
 367,
 13378441,
 13395383,
 16085723,
 18402681,
 29821,
 6372323,
 3310,
 18385367,
 13860,
 613,
 30621,
 10947670,
 11627611,
 89589341,
 15704905,
 36674463,
 15667,
 4655,
 63475,
 17084968,
 14043,
 4922202,
 14844304,
 88254662,
 157,
 31818,
 5889,
 1182,
 4068,
 77050518,
 11975,
 7468,
 13640327,
 3649407,
 11077183,
 6986882,
 11620775,
 17730,
 4718,
 47856619,
 568,
 4711,
 1934313,
 24203975,
 17880,
 26666,
 380,
 2397082,
 62436625,
 11121,
 81658,
 18152,
 6391,
 1082126,
 45576,
 24828418,
 50215757,
 29522,
 8304,
 58318737,
 1881,
 3204206,
 15893979,
 3183404,
 8982440,
 38829050,
 25445,
 18186213,
 12683126,
 12967790,
 46650238,
 22041839,
 2322425,
 10425739,
 10423929,
 125638,
 22616,
 26097,
 31366,
 3708,
 19010386,
 110052768,
 10828524,
 42745,
 6252,
 21671,
 17952,
 27478957,
 17056,
 10521722,
 117651183,
 11706,
 9000,
 4483183,
 24139115,
 33565,
 28214255,
 ...]

In [19]:
def dropCategories(df, col, threshold):
    drop_list = df[col].value_counts()[threshold:].index.to_list()
    df[col].cat.remove_categories(drop_list, inplace=True)
    return df

In [20]:
repos_cur = mc['github']['projects'].find({"_id": {"$in": good_rids}}, ['url', 'language', 'created_at', 'updated_at'])
repos_emb_cur = mc['github']['repos_stars_embeddings'].find({"_id": {"$in": good_rids}})

In [21]:
repos_df = pd.DataFrame(list(repos_cur)).set_index('_id')[['url', 'language', 'created_at', 'updated_at']]
repos_df.language = repos_df.language.astype("category")
repos_df = dropCategories(repos_df, "language", 42)
repos_df

,url,language,created_at,updated_at
_id,,,,
6,cocos2d/cocos2d-x,C++,2010-11-18 23:17:00,2019-02-26 20:51:59
19,samuelclay/NewsBlur,Objective-C,2009-01-05 14:00:43,2019-02-26 03:37:41
29,opencv/opencv,C++,2012-07-19 09:40:17,2016-10-11 14:11:27
34,pockethub/PocketHub,JavaScript,2011-09-08 16:52:50,2016-10-11 14:11:27
37,angular/angular.js,JavaScript,2010-01-06 00:34:37,2019-02-27 03:14:26
49,alexgorbatchev/syntaxhighlighter,NaN,2014-10-07 13:48:58,2019-01-07 05:02:27
55,yui/yui3,JavaScript,2008-12-05 19:12:24,2019-02-26 04:45:11
71,llvm-mirror/llvm,NaN,2012-01-27 23:49:56,2019-02-26 12:59:44
74,joyent/libuv,C,2011-03-29 21:10:45,2019-02-14 03:06:31
92,fnando/i18n-js,JavaScript,2009-09-02 03:35:45,2019-02-25 19:58:58
100,angular/angular-seed,JavaScript,2010-12-24 06:07:50,2019-02-26 05:55:12
102,JakeWharton/Android-ViewPagerIndicator,Java,2011-08-04 15:13:44,1970-01-01 01:00:01
114,madrobby/zepto,HTML,2010-09-20 07:57:57,2019-02-26 04:14:17
116,brandonwamboldt/utilphp,PHP,2012-07-25 00:11:26,2019-02-19 10:42:26
118,ryanb/cancan,Ruby,2009-11-17 01:04:45,2019-02-20 14:34:25
147,JakeWharton/ActionBarSherlock,Java,2011-03-07 17:28:54,2019-02-24 07:22:42
149,substack/node-mkdirp,JavaScript,2011-01-06 02:54:15,2019-02-26 05:33:11
157,wet-boew/wet-boew,HTML,2012-05-11 13:31:20,2019-02-27 02:35:08
168,github/markup,Ruby,2009-10-31 01:02:46,2019-02-27 09:08:08
176,chaplinjs/chaplin,CoffeeScript,2012-02-11 14:14:04,2019-02-19 21:11:42
183,zendframework/zendframework,NaN,2010-06-04 02:42:05,2016-10-11 14:11:41
190,Netflix/SimianArmy,Java,2012-07-06 22:00:05,2019-02-27 07:35:41
202,mozilla-b2g/gaia,JavaScript,2011-09-03 01:38:46,2019-02-22 15:38:38
208,PyCQA/pycodestyle,Python,2009-10-02 00:43:37,2016-10-11 14:15:36
231,celluloid/celluloid,Ruby,2011-03-31 04:05:41,2019-02-25 07:18:42
235,paulirish/infinite-scroll,JavaScript,2010-05-04 15:28:57,1970-01-01 01:00:01
250,AutoMapper/AutoMapper,C#,2010-02-06 15:17:58,2019-02-26 11:35:22
251,stig/json-framework,Objective-C,2010-06-14 22:02:16,2019-02-18 19:58:12
252,rstudio/rstudio,Java,2010-12-07 19:10:25,2019-02-27 06:27:10
274,mislav/will_paginate,Ruby,2008-02-25 20:21:40,2019-02-25 09:17:00
...,...,...,...,...
124542055,aylei/interview,NaN,2019-01-29 08:29:24,2019-02-27 06:40:26
124544988,Ridter/Intranet_Penetration_Tips,NaN,2019-01-29 12:23:51,2019-02-27 02:16:26
124604729,stanfordnlp/stanfordnlp,Python,2017-09-26 08:00:56,2019-02-26 14:21:44
124937980,postlight/mercury-parser,JavaScript,2016-08-23 17:10:28,2019-02-26 13:23:14
124938908,derailed/k9s,Go,2019-01-25 18:46:02,2019-02-26 23:58:01
125140249,NVlabs/stylegan,NaN,2019-02-04 15:33:58,2019-02-27 01:27:16
125169463,pomber/github-history,JavaScript,2019-02-04 21:00:39,2019-02-17 11:02:46
125187465,pomber/git-history,JavaScript,2019-02-04 21:00:39,2019-02-27 01:02:21
125217340,google/clusterfuzz,Python,2019-01-29 00:19:40,2019-02-27 05:50:04
125377471,klaussinani/qoa,JavaScript,2019-01-10 21:57:31,2019-02-26 19:04:37
125408720,instantpage/instant.page,JavaScript,2019-02-07 16:49:59,2019-02-26 10:39:31
125415445,imthenachoman/How-To-Secure-A-Linux-Server,NaN,2019-02-09 06:44:37,2019-02-26 23:54:46
125439728,leon-ai/leon,JavaScript,2019-02-10 12:25:12,2019-02-27 08:19:21
125452655,brightmart/nlp_chinese_corpus,NaN,2019-02-08 14:15:12,2019-02-27 03:33:42
125458836,b3log/vditor,TypeScript,2019-01-24 11:59:59,2019-02-26 10:09:47
125487482,eranyanay/1m-go-websockets,Go,2019-02-10 13:41:43,2019-02-26 16:37:51
125488936,uber/ludwig,Python,2018-12-27 23:58:12,2019-02-27 07:12:22
125598345,github/personal-website,CSS,2019-01-25 00:39:39,2019-02-27 06:16:33
125710596,EBazarov/nsfw_data_source_urls,NaN,2019-02-13 09:21:38,2019-02-27 01:43:19
125796644,JoYoungjoo/SC-FEGAN,Python,2019-02-12 08:52:51,2019-02-27 03:45:14
125842637,LisaDziuba/Awesome-Design-Tools,NaN,2019-02-12 13:55:30,2019-02-26 12:53:24
125869449,openai/gpt-2,Python,2019-02-11 04:21:59,2019-02-26 18:21:58
126042350,infinitered/nsfwjs,JavaScript,2019-02-13 15:06:31,2019-02-26 17:41:10
126163336,taki0112/Tensorflow-Cookbook,NaN,2019-02-16 15:43:31,2019-02-27 02:16:24
126186483,dakshshah96/awesome-startup-credits,NaN,2019-02-16 07:48:56,2019-02-27 06:19:22
126440374,Micropoor/Micro8,NaN,2019-02-18 08:30:52,2019-02-26 09:46:50
126849231,lemire/simdjson,C++,2018-03-23 00:49:18,2019-02-27 01:07:28
126908918,remoteinterview/zero,Python,2018-11-21 21:05:14,2019-02-26 15:33:53
127329472,Microsoft/frontend-bootcamp,TypeScript,2019-02-24 16:11:55,2019-02-26 18:08:00
127439965,smacke/subsync,Python,2019-02-24 02:56:44,2019-02-26 13:37:45

In [22]:
repos_emb_df = pd.DataFrame(list(repos_emb_cur)).set_index('_id')
repos_emb_df

           n_vecs                                                vec
_id
6           13901  [0.24193669855594635, 0.1203954815864563, 0.49...
19           5455  [0.1151142343878746, 0.117125004529953, 0.4360...
29           7744  [0.17094147205352783, -0.06545144319534302, 0....
34           5588  [0.22444790601730347, -0.04315068945288658, 0....
37          56025  [0.23754794895648956, -0.08706655353307724, 0....
49           3550  [0.18847320973873138, -0.02633054554462433, 0....
55           3783  [0.28016871213912964, -0.024500740692019463, 0...
71           3743  [0.32852479815483093, -0.20795677602291107, 0....
74           2289  [0.38658544421195984, -0.2022801786661148, 0.4...
92           2400  [0.15295737981796265, -0.20913812518119812, 0....
100         14461  [0.16231873631477356, -0.2859654724597931, 0.4...
102          2035  [0.20485185086727142, -0.12810784578323364, 0....
114         15462  [0.24657486379146576, -0.1155390813946724, 0.6...
116          1039  [0.17962764203548431, -0.07115256041288376, 0....
118          6989  [0.05643616244196892, -0.33506470918655396, 0....
147          8085  [0.3663099706172943, -0.03676755353808403, 0.2...
149          1877  [0.2927754521369934, -0.2127372920513153, 0.25...
157          1065  [0.08237030357122421, -0.05835690721869469, 0....
168          4232  [0.1618318259716034, -0.07878761738538742, 0.2...
176          3406  [0.17788155376911163, -0.30602723360061646, 0....
183          5975  [0.3110514283180237, -0.0008677131263539195, 0...
190          6457  [0.2259027063846588, -0.1885581761598587, 0.23...
202          2273  [0.021090347319841385, 0.04543430730700493, 0....
208          1132  [0.38395094871520996, 0.20230981707572937, 0.0...
231          3934  [0.04697595164179802, -0.3441542088985443, 0.2...
235          3558  [-0.033795520663261414, -0.10476966947317123, ...
250          6331  [0.28187957406044006, -0.038223717361688614, 0...
251          3705  [0.3464730679988861, 0.01364104263484478, 0.06...
252          2516  [0.22528046369552612, 0.14066027104854584, 0.0...
274          5318  [0.028914978727698326, -0.12691272795200348, 0...
...           ...                                                ...
124542055    1701  [0.24299626052379608, 0.0855366587638855, 0.08...
124544988    1356  [0.868615984916687, 0.047043327242136, -0.2811...
124604729    1501  [0.017220061272382736, -0.08828612416982651, -...
124937980    1400  [0.1524677276611328, 0.2239333689212799, -0.36...
124938908    1201  [0.12023381888866425, -0.11181556433439255, -0...
125140249    4535  [0.2350422590970993, 0.09829267859458923, -0.2...
125169463    2720  [0.26262137293815613, -0.05872228741645813, -0...
125187465    6265  [0.1671777069568634, 0.11873919516801834, -0.1...
125217340    3157  [0.1593889594078064, 0.05925646051764488, -0.0...
125377471    1507  [0.24442675709724426, -0.11182770133018494, 0....
125408720    2677  [0.07869204133749008, 0.15221364796161652, -0....
125415445    7333  [0.15358462929725647, 0.1839389204978943, 0.19...
125439728    4175  [0.044312652200460434, 0.2810889482498169, -0....
125452655    1654  [0.17447012662887573, -0.09590268135070801, -0...
125458836    1311  [-0.013159125111997128, 0.16794109344482422, -...
125487482    2882  [0.3345673680305481, -0.28582763671875, -0.021...
125488936    3203  [0.1222035139799118, -0.07048502564430237, -0....
125598345    2392  [-0.0508757121860981, 0.21556657552719116, -0....
125710596    1833  [0.049868613481521606, -0.13575969636440277, -...
125796644    1543  [0.16230899095535278, 0.04265982657670975, -0....
125842637    4610  [0.2343885451555252, 0.5176398158073425, -0.25...
125869449    3724  [0.19004635512828827, -0.13773779571056366, 0....
126042350    1411  [0.14434276521205902, -0.14065782725811005, -0...
126163336    1622  [-0.16321051120758057, 0.06738749146461487, -0...
126186483    1278  [0.35318779945373535, 0.12867775559425354, -0....
126440374    8073  [0.39079993963241577, 0.13078127801418304, -0....
126849231    4495  [0.2425597906112671, -0.07392888516187668, -0....
126908918    1136  [0.011417683213949203, -0.034034885466098785, ...
127329472    1805  [0.09876284748315811, 0.1406322419643402, -0.1...
127439965    1970  [0.21527761220932007, 0.09439906477928162, -0....

[18722 rows x 2 columns]

In [25]:
repos_emb_df.columns = ['n_vecs', 'embeddings']
repos_df = repos_df.join(repos_emb_df)
repos_df

ValueError: columns overlap but no suffix specified: Index(['n_vecs', 'embeddings'], dtype='object')

In [26]:
repos_df.language.value_counts()

JavaScript          3920
Java                1700
Python              1607
Go                   843
Objective-C          718
C++                  691
PHP                  667
C                    630
Ruby                 585
HTML                 462
Swift                453
C#                   362
CSS                  349
Shell                338
TypeScript           196
Rust                 110
VimL                 108
CoffeeScript         101
Scala                 99
Jupyter Notebook      87
Clojure               59
Lua                   47
Vue                   44
Kotlin                42
Haskell               39
Emacs Lisp            32
Perl                  29
Makefile              26
TeX                   26
R                     25
PowerShell            23
Elixir                22
OCaml                 21
Groovy                19
Erlang                19
Assembly              17
Dart                  15
Objective-C++         12
Matlab                11
Common Lisp            7
PLpgSQL                6
Crystal                6
Name: language, dtype: int64

In [28]:
repos_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18670 entries, 6 to 127439965
Data columns (total 6 columns):
url           18670 non-null object
language      14573 non-null category
created_at    18670 non-null datetime64[ns]
updated_at    18670 non-null datetime64[ns]
n_vecs        18670 non-null int64
embeddings    18670 non-null object
dtypes: category(1), datetime64[ns](2), int64(1), object(2)
memory usage: 1.5+ MB

In [25]:
repos_df.to_pickle("./tb/embeddings/repos_1k_gte10k.pkl")

In [14]:
repos_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 970 entries, 6 to 119888241
Data columns (total 4 columns):
url           970 non-null object
language      764 non-null category
created_at    970 non-null datetime64[ns]
updated_at    970 non-null datetime64[ns]
dtypes: category(1), datetime64[ns](2), object(1)
memory usage: 32.8+ KB

## Followers

In [199]:
followers_model_name = 'users_followers_emb_sg_d300_w30_mc3_e5'
followers_model = Word2Vec.load('./models/' + followers_model_name + '.bin')
print(followers_model)

Word2Vec(vocab=1446832, size=300, alpha=0.025)

In [222]:
followers_good_uids = []

for uid, r in model.wv.vocab.items():
    if r.count >= 100:
        followers_good_uids.append(int(uid))
len(followers_good_uids)

24435

In [223]:
followers_users_cur = mc['github']['users'].find({"_id": {"$in": followers_good_uids}}, 
                                       ['login', 'type', 'fake', 'location', 'deleted', 'country_code', 'created_at'])
followers_users_emb_cur = mc['github']['users_followers_embeddings'].find({"_id": {"$in": followers_good_uids}})

followers_users_df = pd.DataFrame(list(followers_users_cur)).set_index('_id')[
    ['login', 'type', 'fake', 'location', 'deleted', 'country_code', 'created_at']
]
followers_users_emb_df = pd.DataFrame(list(followers_users_emb_cur)).set_index('_id')
followers_users_emb_df.columns = ['n_vecs', 'embeddings']
followers_users_df = followers_users_df.join(followers_users_emb_df)
followers_users_df

,login,type,fake,location,deleted,country_code,created_at,n_vecs,embeddings
_id,,,,,,,,,
2,jmettraux,USR,False,Hiroshima,False,jp,2008-03-22 00:37:42,430,"[0.2063964605331421, 0.3219830095767975, 0.054..."
4,kennethkalmer,USR,False,"Johannesburg, South Africa",False,za,2008-04-28 17:25:53,102,"[0.2238793522119522, 0.2812013626098633, 0.088..."
7,hasimo,USR,False,Tokyo/Japan,False,jp,2008-09-30 00:05:24,256,"[0.3436596989631653, 0.6199936866760254, -0.04..."
10,mcollina,USR,False,In the clouds above Italy,False,None,2009-02-05 21:24:19,371,"[0.32903146743774414, 0.4905785024166107, 0.22..."
47,l4u,USR,False,Hong Kong,False,hk,2009-06-22 14:13:10,309,"[0.3731025159358978, 0.5073902010917664, 0.017..."
49,corefan,USR,False,None,False,None,2012-03-18 01:43:30,386,"[0.33945879340171814, -0.07949918508529663, 0...."
58,hcilab,ORG,False,"Fredericton, New Brunswick, Canada",False,ca,2012-04-04 03:12:28,21738,"[0.38965266942977905, 0.8585405349731445, 0.42..."
70,rafacm,USR,False,Vienna,False,at,2010-07-22 03:58:01,129,"[0.28958895802497864, 0.16287967562675476, 0.1..."
109,jfirebaugh,USR,False,"San Francisco, CA",False,us,2009-06-24 18:01:39,127,"[0.18331538140773773, 0.30185845494270325, 0.1..."
145,Mirocow,USR,False,Russia Moscow,False,ru,2010-08-26 01:03:57,189,"[0.27750810980796814, 0.2190338373184204, 0.18..."
150,myabc,USR,False,"Oxford, England",False,gb,2008-02-24 18:04:05,220,"[0.2900802791118622, 0.3460484743118286, 0.078..."
215,whitten,USR,False,"North Carolina, USA",False,us,2011-12-05 19:59:52,368,"[0.21629151701927185, 0.2949243485927582, 0.08..."
230,laforge49,USR,False,"Brooklyn, NY",False,us,2011-06-11 03:51:36,209,"[0.27668672800064087, 0.013871472328901291, 0...."
243,timepilot,USR,False,None,False,None,2009-04-25 15:27:19,131,"[0.3317778706550598, 0.4452219009399414, 0.009..."
245,jefftriplett,USR,False,"Lawrence, KS",False,us,2009-01-30 16:42:25,163,"[0.21275418996810913, 0.4239075481891632, 0.13..."
246,jasonmelgoza,USR,False,"Santa Maria, California",False,None,2009-05-29 16:20:22,580,"[0.3451193571090698, 0.7721948027610779, 0.255..."
247,philippWassibauer,USR,False,"Berlin, Germany",False,de,2008-09-02 09:52:29,107,"[0.2988734841346741, 0.42635872960090637, 0.05..."
248,matagus,USR,False,"Buenos Aires, Argentina",False,ar,2009-02-27 09:45:55,2251,"[0.46278005838394165, 0.6849187016487122, 0.34..."
259,djacobs,USR,False,New York City,False,us,2008-12-23 04:28:57,231,"[0.2675457298755646, 0.4995808005332947, 0.032..."
262,slouis,USR,False,None,False,None,2010-08-01 12:21:40,115,"[0.27421048283576965, 0.2436159998178482, 0.14..."
264,heliostatic,USR,False,"Williamstown, MA",False,None,2009-04-06 05:06:36,313,"[0.33055996894836426, 0.6172380447387695, 0.09..."
266,diegopacheco,USR,False,"Porto Alegre, RS - Brazil",False,br,2009-08-30 23:05:23,125,"[0.3167843818664551, 0.3806687891483307, 0.145..."
277,fractal,USR,False,London,False,gb,2009-09-11 10:57:19,152,"[0.41729286313056946, 0.24611705541610718, 0.0..."
288,redaready,USR,False,"Aix en provence, France",False,fr,2009-08-18 20:16:32,139,"[0.32805371284484863, 0.2765505313873291, 0.16..."
300,plokhotnyuk,USR,False,"Kraków, Poland",False,pl,2011-07-02 09:07:47,277,"[0.5079621076583862, 0.3359842002391815, 0.077..."
301,folone,USR,False,"London, UK",False,gb,2010-08-16 14:15:49,195,"[0.48098695278167725, 0.34136834740638733, 0.0..."
302,equus12,USR,False,NaN,True,None,2012-04-16 07:13:33,13500,"[0.4559532105922699, 0.9383670091629028, 0.351..."
303,Marak,USR,False,"New York City, New York",False,us,2009-04-03 01:34:57,2221,"[0.29924941062927246, 0.7216456532478333, 0.44..."
304,jdavis,USR,False,"Seattle, Washington",False,us,2009-11-24 21:39:39,378,"[0.2711787223815918, 0.5325055122375488, 0.218..."
307,stonegao,USR,False,Beijing,False,cn,2008-12-22 10:19:45,1788,"[0.45086565613746643, 0.8540741801261902, 0.25..."
...,...,...,...,...,...,...,...,...,...
46405322,GCQuantCapital,USR,False,None,False,None,2018-08-14 07:25:21,140,"[0.10242456942796707, -0.07068628072738647, 0...."
46405451,BlockRecruit,USR,False,None,False,us,2016-09-29 04:05:56,107,"[0.06205707788467407, -0.0836508646607399, 0.2..."
46405554,PrasanthiPayyala,USR,False,None,False,None,2018-06-04 05:26:07,128,"[0.3390811085700989, 0.016605177894234657, 0.1..."
46405555,haomengjie,USR,False,None,False,None,2016-03-22 07:53:55,101,"[0.5450181365013123, -0.07282359898090363, 0.1..."
46405580,diegotres-zz,USR,False,None,False,br,2008-12-08 13:14:25,100,"[0.23534852266311646, 0.17514380812644958, 0.0..."
46405960,sajjadh47,USR,False,None,False,None,2016-01-18 08:19:05,115,"[0.31356993317604065, 0.06470789760351181, 0.1..."
46406120,ListoBrands,USR,False,None,False,gb,2018-05-11 10:12:53,653,"[0.04023820161819458, 0.07540177553892136, 0.1..."
46406340,jessicazhouyuwei,USR,False,None,False,None,2016-05-03 15:23:37,138,"[0.34009668231010437, 0.025523191317915916, 0...."
46406478,Wingli001,USR,False,None,False,None,2018-07-31 10:52:39,127,"[0.06867655366659164, -0.1261308193206787, 0.1..."
46406509,shirlyba,USR,False,None,False,None,2018-05-15 04:34:29,153,"[0.12094971537590027, -0.03406088054180145, 0...."
46406530,gogofunc,USR,False,None,False,None,2011-06-15 10:29:51,161,"[0.37695005536079407, -0.02834065444767475, 0...."
46406662,ThwaitesEdenSmith,USR,False,None,False,None,2018-09-26 10:58:19,103,"[0.3776489794254303, 0.16623662412166595, -0.0..."
46406763,evamorano,USR,False,None,False,None,2011-11-04 11:35:19,116,"[0.12884306907653809, -0.17129066586494446, 0...."
46406788,mkfifo,USR,False,None,False,None,2009-04-19 21:24:59,170,"[0.22164839506149292, 0.12075101584196091, 0.0..."
46406874,manikur,USR,False,None,False,None,2018-08-05 15:47:16,135,"[0.12494443356990814, -0.2770724892616272, 0.1..."
46406900,andresoct,USR,False,None,False,None,2012-05-14 19:43:03,167,"[0.2851473093032837, 0.07321155816316605, 0.29..."
46406904,bunnygens,USR,False,None,False,None,2018-04-02 13:41:12,162,"[0.6210293173789978, -0.04702051728963852, 0.1..."
46406946,JWhitby,USR,False,None,False,None,2018-05-31 16:54:31,207,"[0.19868114590644836, -0.009701469913125038, -..."
46407129,ma-ag,USR,False,None,False,None,2018-05-09 17:52:37,254,"[0.26094046235084534, -0.0063535310328006744, ..."
46407677,Tlopasha,USR,False,None,False,None,2014-10-17 15:12:56,108,"[0.20342372357845306, 0.22365693747997284, -0...."
46407981,chinmoy-mbstu,USR,False,None,False,bd,2016-08-05 18:41:22,146,"[0.37205028533935547, 0.026598375290632248, 0...."
46407982,cirodilanno,USR,False,None,False,None,2018-06-12 00:12:17,122,"[0.3325481712818146, 0.08617851883172989, 0.12..."
46408019,Nelvita,USR,False,None,False,None,2018-04-27 12:57:47,106,"[0.04583774507045746, -0.10003423690795898, 0...."
46408824,hij24,USR,False,None,False,None,2018-06-20 19:42:47,117,"[0.1618928164243698, 0.01660524122416973, 0.07..."
46409115,rodrigofrontsp,USR,False,None,False,br,2013-01-17 13:09:41,117,"[0.32905665040016174, 0.2282107025384903, 0.15..."
46409138,zhaoxiaodao123,USR,False,None,False,None,2017-11-01 08:14:27,123,"[0.369720458984375, 0.01275634765625, 0.150544..."
46411645,Michellecoughlan,USR,False,None,False,gb,2018-08-08 09:06:51,109,"[0.10528992861509323, 0.04763873666524887, 0.1..."
46412385,ddsferreira,USR,False,None,False,gb,2010-10-07 09:22:58,162,"[0.2581738829612732, 0.15989001095294952, 0.00..."
46434150,cmFodWx5YWRhdjEyMTA5,USR,False,None,False,in,2015-07-21 12:48:09,155,"[0.48079538345336914, -0.07317670434713364, 0...."
46450413,soluable,USR,False,None,False,None,2016-06-08 02:56:03,100,"[0.4660983681678772, -0.11688192188739777, 0.1..."

In [224]:
followers_users_df.to_pickle("./tb/embeddings/users_followers_24k_gte100.pkl")

## Following

In [225]:
following_model_name = 'users_following_emb_sg_d300_w30_mc3_e5'
following_model = Word2Vec.load('./models/' + following_model_name + '.bin')
print(following_model)

Word2Vec(vocab=1385758, size=300, alpha=0.025)

In [244]:
following_good_uids = []

for uid, r in following_model.wv.vocab.items():
    if r.count >= 1_000:
        following_good_uids.append(int(uid))
len(following_good_uids)

1537

In [245]:
following_users_cur = mc['github']['users'].find({"_id": {"$in": following_good_uids}}, 
                                       ['login', 'type', 'fake', 'location', 'deleted', 'country_code', 'created_at'])
following_users_emb_cur = mc['github']['users_following_embeddings'].find({"_id": {"$in": following_good_uids}})

following_users_df = pd.DataFrame(list(following_users_cur)).set_index('_id')[
    ['login', 'type', 'fake', 'location', 'deleted', 'country_code', 'created_at']
]
following_users_emb_df = pd.DataFrame(list(following_users_emb_cur)).set_index('_id')
following_users_emb_df.columns = ['n_vecs', 'embeddings']
following_users_df = following_users_df.join(following_users_emb_df)
following_users_df

,login,type,fake,location,deleted,country_code,created_at,n_vecs,embeddings
_id,,,,,,,,,
10,mcollina,USR,False,In the clouds above Italy,False,None,2009-02-05 21:24:19,2574,"[-0.13591870665550232, 0.30812159180641174, -0..."
27,jimweirich,USR,False,Cincinnati,False,us,2008-03-27 18:19:22,1905,"[-0.5672861933708191, 0.192423477768898, -0.17..."
78,samuelclay,USR,False,"Cambridge, Massachusetts",False,us,2009-01-05 03:46:08,1295,"[-0.44099417328834534, 0.1900487095117569, -0...."
129,tenderlove,USR,False,Seattle,False,us,2008-03-14 19:04:17,7904,"[-0.43326085805892944, 0.38780757784843445, -0..."
189,hmason,USR,False,"New York, NY",False,us,2008-07-22 15:55:09,3413,"[-0.27972522377967834, 0.024197496473789215, -..."
216,fredwu,USR,False,"Melbourne, Australia (& Shanghai, China)",False,None,2008-10-31 03:34:48,1244,"[-0.7697437405586243, -0.10295889526605606, -0..."
272,yui,ORG,False,"Sunnyvale, CA",False,us,2008-12-04 00:46:11,1270,"[-0.8946189284324646, -0.1585889607667923, -0...."
303,Marak,USR,False,"New York City, New York",False,us,2009-04-03 01:34:57,2436,"[-0.42212310433387756, 0.15440842509269714, -0..."
376,tianyicui,USR,False,New York City,False,us,2009-02-09 13:50:20,1614,"[-0.5902652144432068, 0.044978946447372437, -0..."
412,sjl,USR,False,"Rochester, NY",False,us,2009-02-26 20:20:05,2247,"[-0.48881471157073975, 0.06565481424331665, -0..."
418,ask,USR,False,"Palo Alto, CA",False,us,2008-02-28 11:11:11,1486,"[-0.5789979100227356, 0.06390038132667542, -0...."
465,andrew,USR,False,"Somerset, UK",False,gb,2008-02-27 10:39:22,2145,"[-0.5339071154594421, 0.23833924531936646, -0...."
540,hmert,USR,False,San Francisco,False,us,2010-01-15 10:58:43,1155,"[-0.42308688163757324, 0.09906024485826492, -0..."
640,javiereguiluz,USR,False,Vitoria-Gasteiz (Spain),False,None,2009-04-13 18:26:53,1222,"[-0.594545304775238, 0.315415620803833, -0.376..."
651,passy,USR,False,"London, UK",False,gb,2008-05-10 22:30:07,1965,"[-0.30136358737945557, 0.006547853350639343, -..."
775,josephmisiti,USR,False,"NYC, NY",False,us,2010-04-17 19:09:13,1933,"[-0.507480800151825, -0.03392593562602997, -0...."
796,kennethreitz,USR,False,"Winchester, VA, USA",False,None,2009-08-26 19:17:47,26278,"[-0.3248744010925293, -0.1124860942363739, 0.0..."
858,willdurand,USR,False,Germany,False,de,2010-03-07 13:15:48,1311,"[-0.5183705687522888, 0.1216478943824768, -0.0..."
859,stof,USR,False,Paris,False,fr,2010-10-14 11:56:42,1772,"[-0.7090374827384949, 0.24040597677230835, -0...."
877,fnando,USR,False,"Vancouver, Canada",False,ca,2008-03-13 15:15:49,1779,"[-0.49663135409355164, 0.30495375394821167, -0..."
896,JakeWharton,USR,False,"Pittsburgh, PA, USA",False,us,2009-03-24 15:09:53,48553,"[-0.3691677749156952, 0.29243144392967224, -0...."
963,bnoordhuis,USR,False,The Netherlands,False,nl,2010-05-13 18:10:19,2140,"[-0.47398948669433594, -0.07268083840608597, -..."
974,piscisaureus,USR,False,Amsterdam,False,nl,2010-03-08 09:24:21,1090,"[-0.2208438664674759, 0.07491111010313034, -0...."
979,IgorMinar,USR,False,"SF Bay Area, CA",False,us,2010-03-05 02:31:28,3047,"[-0.49191123247146606, 0.2117009311914444, -0...."
986,vojtajina,USR,False,San Francisco Bay Area,False,us,2009-01-14 21:58:09,1393,"[-0.4776815176010132, -0.10646376013755798, -0..."
988,mhevery,USR,False,None,False,None,2009-08-04 19:42:41,4018,"[-0.5729660391807556, 0.027157718315720558, -0..."
995,isaacs,USR,False,Oakland CA,False,us,2008-05-04 17:43:46,10123,"[-0.47306028008461, 0.08531314879655838, -0.26..."
1001,philips,USR,False,"San Francisco, CA",False,us,2008-11-09 21:23:48,1169,"[-0.24841341376304626, 0.04404698684811592, -0..."
1019,madrobby,USR,False,"Philadelphia, PA",False,us,2008-03-18 21:11:15,3056,"[-0.8481782078742981, -0.029848607257008553, -..."
1039,nimbupani,USR,False,San Francisco,False,us,2009-04-16 16:38:13,1384,"[-0.3958338499069214, 0.007742552552372217, -0..."
...,...,...,...,...,...,...,...,...,...
31283401,jessfraz,USR,False,PID 1,False,None,2012-02-17 02:15:05,7480,"[-0.864474892616272, 1.2218844890594482, 0.395..."
31539943,bookercodes,USR,False,London,False,gb,2015-04-13 16:07:05,1043,"[0.014114387333393097, -0.17135687172412872, 0..."
32109250,chentao0707,USR,False,"JiangSu,SuZhou",False,None,2014-01-08 02:33:04,1004,"[-0.6737750768661499, 0.4105238616466522, -0.0..."
32374024,AndiChiou,USR,False,MA,False,us,2016-11-14 18:51:20,1197,"[-0.3553171753883362, 0.20091384649276733, 0.3..."
32783976,fourbrother,USR,False,None,False,None,2016-12-05 04:59:56,1197,"[-0.777396023273468, 0.16991011798381805, 0.11..."
32834917,windiest,USR,False,"Forever in your heart, China",False,None,2015-01-29 15:25:34,3108,"[-0.5511199831962585, 1.3019050359725952, 0.48..."
33227533,wangshub,USR,False,"Shenzhen, China",False,cn,2016-08-09 09:03:47,1492,"[-0.5833948254585266, -0.05720055475831032, 0...."
33246172,YunaiV,USR,False,"Shanghai, China",False,cn,2012-07-21 02:30:00,1531,"[-0.8005266189575195, 0.1919742375612259, -0.2..."
33255295,thedaviddias,USR,False,"France, Mauritius, Canada",False,None,2010-04-05 14:40:12,1151,"[0.0074388934299349785, 0.3676488399505615, 0...."
33255883,MylesBorins,USR,False,"New York, New York",False,us,2010-11-27 07:09:52,1080,"[-0.44952908158302307, 0.8341073989868164, 0.1..."
33471268,BilgisayarKavramlari,USR,False,None,False,None,2017-01-15 03:39:51,1519,"[-0.3758212625980377, 0.19838139414787292, -0...."
33579752,dalinhuang99,USR,False,"Ottawa, ON, Canada",False,ca,2014-01-26 20:07:36,3536,"[-0.4906664192676544, -0.6017106771469116, 0.5..."
34329131,ahmetb,USR,False,"Seattle, WA",False,us,2009-11-28 14:59:59,1718,"[-0.9491931796073914, 0.7256838083267212, 0.50..."
34411120,benlesh,USR,False,"San Jose, CA",False,us,2012-03-15 14:24:15,1329,"[-0.466690331697464, 0.06940469890832901, 0.47..."
34697267,trekhleb,USR,False,"Lviv, Ukraine",False,ua,2012-12-09 08:38:00,1441,"[-0.3400801122188568, 6.661932275164872e-05, 0..."
36006750,dplewis,USR,False,UTC-6,False,None,2014-11-18 21:06:39,1062,"[-0.3321850001811981, -0.5203285813331604, 0.1..."
36203854,pantie,USR,False,"Phoenix, AZ, United States",False,us,2017-05-29 07:29:29,1052,"[-0.32352253794670105, -0.3109596371650696, 0...."
36383968,rftHusn,USR,False,None,False,None,2016-08-25 22:45:40,2224,"[-0.6679425835609436, -0.3498700261116028, 0.0..."
37095010,cenaion,USR,False,"CA, USA",False,us,2017-07-18 08:44:53,1044,"[-0.8411409854888916, -0.2091742753982544, 0.4..."
37443674,kbrsh,USR,False,None,False,None,2015-11-04 03:58:57,1316,"[-0.515290379524231, 0.031156858429312706, 0.1..."
37808455,sophiebits,USR,False,California,False,us,2008-04-11 22:42:39,4070,"[-0.40168312191963196, -0.6033268570899963, 0...."
37979674,mohammadhosseinime,USR,False,None,False,None,2016-10-18 15:04:57,1024,"[-0.063239187002182, 0.22308872640132904, 0.30..."
39252399,opengiineer,USR,False,The Internet,False,ru,2017-10-16 06:32:02,1872,"[-0.4791414141654968, -0.6582183837890625, 0.3..."
39280486,nomadbot,USR,False,The Internet,False,ru,2014-10-15 19:25:11,1664,"[-0.6351101398468018, -0.571701169013977, 0.34..."
40537946,indrajithbandara,USR,False,"Diyathalawa, Sri Lanaka",False,None,2016-10-21 08:05:14,1011,"[-0.6270743608474731, -0.5214064717292786, 0.2..."
40612453,EclipseMain,USR,False,Sine Nomine Discord Server,False,None,2017-08-29 01:54:20,1645,"[-0.6186858415603638, -0.6143300533294678, 0.3..."
40653026,FeeiCN,USR,False,"Hangzhou, China",False,cn,2012-04-04 12:01:57,1087,"[-0.3919394016265869, -0.08034150302410126, 0...."
41293861,jamiebuilds,USR,False,None,False,None,2011-08-01 22:33:05,4593,"[0.06772847473621368, -0.2686043381690979, 0.5..."
41319644,CyC2018,USR,False,Guangzhou,False,cn,2018-02-08 09:03:31,1469,"[-0.5039348006248474, -0.22610178589820862, 0...."
41633238,RamotionDev,USR,False,None,False,None,2014-10-01 13:21:47,1804,"[-0.15963387489318848, -0.48752540349960327, -..."

In [246]:
following_users_df.to_pickle("./tb/embeddings/users_following_2k_gte1k.pkl")

## sandbox

In [1]:
fls = !ls ./tb/embeddings/

for f in fls:
    tmp_df = pd.read_pickle(f'./tb/embeddings/{f}')
    print(f'{f} - {len(tmp_df)} - gte{tmp_df["n_vecs"].min()}')

repos_19k_gte1k.pkl - 18670 - gte1000
repos_1k_gte10k.pkl - 970 - gte10002
repos_85k_gte200.pkl - 84806 - gte200
users_followers_24k_gte100.pkl - 24435 - gte100
users_followers_70k_gte50.pkl - 69570 - gte50
users_following_29k_gte100.pkl - 28827 - gte100
users_following_2k_gte1k.pkl - 1537 - gte1000
users_following_88k_gte40.pkl - 88323 - gte40